#!/usr/bin/python3

def raise_exception():
    result = "name" + 5
    return (result)
